---



# START - boilerplate tasks

- name: Load OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ fact_role_path }}/vars/{{ ansible_os_family | lower }}.yml"
      skip: true

- name: "Run any OS specific tasks"
  include: "{{ item }}"
  with_first_found:
    - files:
        - "{{ fact_role_path }}/tasks/{{ ansible_os_family | lower }}.yml"
      skip: true

- name: "Load distribution (centos, ubuntu) default variables"
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ fact_role_path }}/defaults/{{ ansible_distribution | lower }}.yml"
      skip: true

- name: "DEBUG - Debug ansible_role_docker variable values"
  include: "{{ item }}"
  with_first_found:
    - files:
        - "{{ fact_role_path }}/tasks/debug.yml"
      skip: true
  when: ansible_role_docker_debug is defined and ansible_role_docker_debug

# END - boilerplate tasks

# OS Versions

## DEBUGGING

- name: "DEBUG - value of ansible_distribution"
  debug: var=ansible_distribution
  when: ansible_role_docker_debug

- name: "DEBUG - value of ansible_distribution_version"
  debug: var=ansible_distribution_version
  when: ansible_role_docker_debug

- name: "DEBUG - value of ansible_distribution_major_version"
  debug: var=ansible_distribution_major_version
  when: ansible_role_docker_debug

## CentOS

- name: "Run CentOS  specific tasks"
  include_tasks: "centos_.yml"
  static: false
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version| int == ""
  with_distributions:
    - 7
    - 8
    - 9

## Debian

- name: "Run Debian  (Stretch) specific tasks"
  include_tasks: "debian_.yml"
  static: false
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version| int == ""
  with_distributions:
    - 7
    - 8
    - 9

## Ubuntu

- name: "Run Ubuntu  specific tasks"
  include_tasks: "ubuntu_.yml"
  static: false
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == ""
  with_distributions:
      - 12.04
      - 14.04
      - 16.04
      - 17.04
      - 18.04
      - 19.04

- name: "Install necessary packages"
  package:
    - name: python-pip
      state: present
    - name: libssl-dev
      state: present