---
- hosts: docker_servers
  become: no
  gather_facts: true
  pre_tasks:
    - set_fact: fact_role_name="{{ lookup('env','ANSIBLE_ROLE_NAME') }}"
    - debug: var=fact_role_name
    - set_fact: fact_role_path="{{ lookup('pipe','pwd') }}/ansible_role_docker"
    - debug: var=fact_role_path
  roles:
    - ansible-role-docker
